(dp1
S'output'
p2
S'<class \'_mysql_exceptions.ProgrammingError\'> (1146, "Table \'cssow.sow_learning_episode__has__learning_objective\' doesn\'t exist")'
p3
sS'layer'
p4
S'C:\\Dev\\cssow_web2py\\src\\applications\\schemeofwork\\controllers/learningobjective.py'
p5
sS'code'
p6
S'<code object <module> at 077601D0, file "C:\\Dev\\cssow_web2py\\src\\applications\\schemeofwork\\controllers/learningobjective.py", line 2>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "C:\\Dev\\cssow_web2py\\src\\gluon\\restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "C:\\Dev\\cssow_web2py\\src\\applications\\schemeofwork\\controllers/learningobjective.py", line 87, in <module>\n  File "C:\\Dev\\cssow_web2py\\src\\gluon\\globals.py", line 421, in <lambda>\n    self._caller = lambda f: f()\n  File "C:\\Dev\\cssow_web2py\\src\\gluon\\tools.py", line 3867, in f\n    return action(*a, **b)\n  File "C:\\Dev\\cssow_web2py\\src\\applications\\schemeofwork\\controllers/learningobjective.py", line 73, in save_item\n    learningobjectiveModel.save(auth.user.id)\n  File "applications/schemeofwork/models/learningobjectiveModel.py", line 238, in save\n    rval = model._insert()\n  File "applications/schemeofwork/models/learningobjectiveModel.py", line 81, in _insert\n    db.executesql(str_insert2)\n  File "C:\\Dev\\cssow_web2py\\src\\gluon\\packages\\dal\\pydal\\base.py", line 772, in executesql\n    adapter.execute(query)\n  File "C:\\Dev\\cssow_web2py\\src\\gluon\\packages\\dal\\pydal\\adapters\\__init__.py", line 67, in wrap\n    return f(*args, **kwargs)\n  File "C:\\Dev\\cssow_web2py\\src\\gluon\\packages\\dal\\pydal\\adapters\\base.py", line 413, in execute\n    rv = self.cursor.execute(command, *args[1:], **kwargs)\n  File "MySQLdb/cursors.py", line 205, in execute\n  File "MySQLdb/connections.py", line 36, in defaulterrorhandler\nProgrammingError: (1146, "Table \'cssow.sow_learning_episode__has__learning_objective\' doesn\'t exist")\n'
p11
s.